### ISSUE TITLE
bug(icon): nf-mdi-corn has been removed

### ISSUE THREAD

**Issue by CAESIUS-TIM** [hafiz-muhammad/configs#1]
![image](https://github.com/hafiz-muhammad/configs/assets/60285058/4e7a63af-a32b-46e6-bffb-2bfa7d83aaac)

https://github.com/hafiz-muhammad/configs/blob/6b5994571fd75c489b585b5253917b860c9ea70b/archived/neofetch/config.conf#L8

**Comment by hafiz-muhammad** [comment]
Thank you for raising this issue. Icons have been updated.
